# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1697a76de15254ac046506027376a53c6494dc2671e771ac5853dd2e98757eac7916985738e67ba20b47de09bbcc0bb089bb352bab10afa06585ff28bdfe02f

test:
  secret_key_base: 2c23260e264347d01f85c77f527cce03b71e04b7038116274ee436d9c24a1f78c84476f1d6f917d9a984db2b8adf6b11d1392e03b33340c610660202ed76b187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
